version: '3'
services:

  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=workload
      - POSTGRES_DB=workload
    ports:
      - "5432:5432"

  workload-manager:
    image: szymon2kozlowski/workload-manager:0.2.4
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 256M
    ports:
      - "9000:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=workload
      - APP_CONNECTION_PRIME_URL=http://prime-number-worker:8081
      - APP_CONNECTION_PRIME_RANDOM_PATH=/api/prime/random
      - APP_CONNECTION_CYPHER_URL=http://cypher-worker:8082
      - APP_CONNECTION_CYPHER_ENCRYPT_PATH=/api/cypher/encrypt
      - APP_CONNECTION_CYPHER_DECRYPT_PATH=/api/cypher/decrypt
      - APP_CONNECTION_CYPHER_KEYS_PATH=/api/cypher/keys
    depends_on:
      - db
      - cypher-worker
      - prime-number-worker

  cypher-worker:
    image: szymon2kozlowski/cypher-worker:0.2.1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 256M
    ports:
      - "9002:8082"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=cypher
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.112.1/workload?currentSchema=cypher
      - APP_CYPHER_KEY_SIZE=1024
    depends_on:
      - db

  prime-number-worker:
    image: szymon2kozlowski/prime-number-worker:0.2.1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 256M
    ports:
      - "9001:8081"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=prime
      - APP_PRIME_ARRAY_SIZE_MAX=1000
    depends_on:
      - db

  prometheus:
    image: szymon2kozlowski/workload-prometheus:0.0.1-SNAPSHOT
    container_name: prometheus-container
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

  tester:
    image: szymon2kozlowski/workload-tester:0.0.1-SNAPSHOT
    container_name: tester-container
    environment:
      - WORKLOAD_MANAGER_URL=http://workload-manager-workload-manager-1:8080/api/user
      - WORKLOAD_MANAGER_START_PATH=/start
      - WORKLOAD_MANAGER_TASK_PATH=/task/create
      - TEST_SET=1

volumes:
  pg_data:
