version: '3'
services:

  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=workload
      - POSTGRES_DB=workload
    ports:
      - "5432:5432"

  workload-manager:
    image: szymon2kozlowski/workload-manager:0.1.0
    ports:
      - "9000:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=workload
      - APP_CONNECTION_PRIME_URL=http://workload-manager-prime-number-worker-1:8081
      - APP_CONNECTION_PRIME_RANDOM_PATH=/primeGenerator
      - APP_CONNECTION_CYPHER_URL=http://workload-manager-cypher-worker-1:8082
      - APP_CONNECTION_CYPHER_ENCRYPT_PATH=/encrypter
      - APP_CONNECTION_CYPHER_DECRYPT_PATH=/decrypter
      - APP_CONNECTION_CYPHER_KEYS_PATH=/keyGenerator
    depends_on:
      - db
      - cypher-worker
      - prime-number-worker

  cypher-worker:
    image: szymon2kozlowski/cypher-worker:0.1.0
    ports:
      - "9002:8082"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=cypher
    depends_on:
      - db

  prime-number-worker:
    image: szymon2kozlowski/prime-number-worker:0.1.0
    ports:
      - "9001:8081"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=prime
    depends_on:
      - db

  prometheus:
    image: szymon2kozlowski/workload-prometheus:0.0.1-SNAPSHOT
    container_name: prometheus-container
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:9.1.4
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

volumes:
  pg_data:
