version: '3'
services:

  db:
    image: postgres:12-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=workload
      - POSTGRES_DB=workload
    ports:
      - "5432:5432"

  workload-manager:
    image: szymon2kozlowski/workload-manager:0.0.6-SNAPSHOT
    ports:
      - "9000:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=workload
      - APP_CONNECTION_PRIME_URL=http://workload-manager-prime-number-worker-1:8081/api/prime
      - APP_CONNECTION_CYPHER_URL=http://workload-manager-cypher-worker-1:8082/api/cypher
    depends_on:
      - db
      - cypher-worker
      - prime-number-worker

  cypher-worker:
    image: szymon2kozlowski/cypher-worker:0.0.4-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=cypher
    depends_on:
      - db

  prime-number-worker:
    image: szymon2kozlowski/prime-number-worker:0.0.3-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_USERNAME=workload
      - SPRING_DATASOURCE_PASSWORD=abc123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/workload?currentSchema=prime
    depends_on:
      - db

volumes:
  pg_data:
