server:
  port: 8080
app:
  connection:
    prime:
      url: http://localhost:8081
    cypher:
      url: http://localhost:8082

spring:
  reactor:
    netty:
      pool:
        maxIdleTime: 45000
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/workload?currentSchema=workload
    username: workload
    password: abc123
  jpa:
    properties:
      hibernate:
        default_schema: workload

reactor:
  netty:
    http:
      client: DEBUG

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true